version: 0.0.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
configuration: Release
before_build:
- nuget restore
build:
  verbosity: minimal
on:
  branch: master                 # release from master branch only
  appveyor_repo_tag: true        # deploy on tag push only
artifacts:
  path: '*.exe'
deploy:
  provider: GitHub
  auth_token:
    secure: lBtYei2XwIlzt9TMhyP8cmDleas5+/qQzT1AXqtGQb7+F6L/9Z+ubzQGykGPx4yB

