version: 0.0.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
configuration: Release
before_build:
- nuget restore
build:
  verbosity: minimal
deploy:
- provider: GitHub
